ublox_gps_node:
  ros__parameters:
    debug: 1                    # Range 0-4 (0 means no debug statements will print)
    sensor_fusion: false        # false set, it will work as rtcm mode and will ignore /velocity_data
                                # true  set,  rtcm mode will not work  and will take  /velocity_data
    imu_offset: true
    save:                            
      mask: 3103                # Save I/O, Message, INF Message, Nav, Receiver
                                # Manager, Antenna, and Logging Configuration
      device: 4                 # Save to EEPROM

    device: /dev/ttyACM0
    frame_id: gps
    rate: 1.0                   # in Hz
    nav_rate: 1                 # [# of measurement cycles], recommended 1 Hz, may
                                # be either 5 Hz (Dual constellation) or
                                # 8 Hz (GPS only)
    dynamic_model: portable     # Airborne < 2G, 2D fix not supported (3D only),
                                # Max Alt: 50km
                                # Max Horizontal Velocity: 250 m/s,
                                # Max Vertical Velocity: 100 m/s
    fix_mode: auto
    enable_ppp: false
    dr_limit: 2
    use_adr: true

    # TMODE3 Config
    tmode3: 0                   # Survey-In Mode
    sv_in:
      reset: false              # True: disables and re-enables survey-in (resets)
                                # False: Disables survey-in only if TMODE3 is
                                # disabled
      min_dur: 300              # Survey-In Minimum Duration [s]
      acc_lim: 3.0              # Survey-In Accuracy Limit [m]

    gnss:
      glonass: true             
      beidou: false            
      qzss: true                

    dgnss_mode: 3               # Fixed mode

    inf:
      all: true                 # Whether to display all INF messages in console

    # Enable u-blox message publishers
    publish:
      all: true
      aid:
        hui: true
      esf:
        all: true
      nav:
        posecef: false
